### PR TITLE
Parse more rules and tests

### PR DESCRIPTION
**Pull request by fatteneder**
Hi,

I saw you asked for help over at https://github.com/JuliaSymbolics/Symbolics.jl/issues/58#issuecomment-1094339557, so I thought I give it a shot.

### Contents

Spoiler: I mixed a few tasks in this PR. If you want, I can split them up into two PRs if desired.

This PR adds 
- the tests from the Rubi site
- a parser to read the tests into `WExpr`
- a parser to read the rules into `WExpr` (should substitute `all_rules`, see below)
- a script to extract a list of (hopefully) all functions that will be needed to implement the rules with

I think right now `all_rules` does the parsing into `WExpr` and immediately applies syntax transformation to obtain code that can be used for `Metatheory.jl`. Given there are lots of rules and even more tests to parse, I thought it might be better to divide the parsing into three stages:
1. Parse rules/tests into `MathLink.WExpr`s.
2. Unwrap the rules/tests, e.g. strip the `If[$LoadShowStep, ...` clauses etc.
3. Apply syntax transformations to the actual rules and their conditions so that we can generate the Julia rules with `Metatheory.jl`.

This way you only have to do the expensive step of parsing the expressions using the `Wolfram Engine` once and then can cache the result. Later you can then (possibly with multi-threading; might only be relevant for the tests) repeatedly apply the unwrapping and syntax transformations as needed. I think this makes it also quite convenient for development.

### Questions

- Which version of Rubi did you upload in this repo? The version appearing here https://github.com/RuleBasedIntegration/Rubi/blob/master/Rubi/IntegrationRules/1%20Algebraic%20functions/1.1%20Binomial%20products/1.1.1%20Linear/1.1.1.1%20(a%2Bb%20x)%5Em.m (last updated 4 years ago) has the rules organized nicely in one lines each (similar to the tests). This makes it simpler to parse and also avoids to manually edit some files to remove newlines in `If[$LoadShowStep, ...` clauses.
- Do you already have a strategy on how to translate the rules to `Metatheory` and `Symbolics` compatible syntax?

### Other

Lastly, regarding your concerns about the usefulness and effectiveness of this pkg: The rules and tests have to be parsed anyways if someone wants to port `Rubi` to Julia. So I think this already justifies this package :) Whether using `MathLink` is effective or not can only be judged on a concrete implementation.

### CODE REVIEW

**Comment by fatteneder** [comment]
This PR is finished now.

I added the files `gen/scripts/parse_rules.jl` (replaces `SymbolicRubiGen.all_rules`) and `gen/scripts/parse_tests.jl` which do now the parsing, unwrapping and rewriting in separate steps. The parsed Mathematica expressions are now cached, so that when you repeatedly re-including those files you only redo the transformations.

Right now this branch recognizes 6923 rules and 72945 tests.

When refactoring `all_rules` I disabled a few of the replacement functions in `fdict`, e.g. `Power, Blank, Pattern, Optional`, since they either caused errors or slowed down everything (espcially `Power => SymbolicUtils.Pow`). This should be addressed next when implementing the mathematica-to-julia transformations.


Regarding this question:
> Do you already have a strategy on how to translate the rules to Metatheory and Symbolics compatible syntax?

I extended `gen/scripts/gather_functions.jl` so that it now also records which rules file and test file require which functions to be implemented, sorted from least to most. The output is written into `gen/scripts/required_functions.md`. Perhaps a starting point for translating rules would be to look at this file and implement those of the rules and test files that need the least to be to work. This way we could get tests working as soon as possible and then incrementally add more. PS: For `gather_functions.jl` to work you have to `dev` the `SymbolicRubi` package from within `SymbolicRubiGen`. Not ideal, but it works for now.

I also gathered notes on some of the functions. Perhaps they can be of help too.
```md
# likely to require type from Symbolics.jl
SqrtNumberQ
SqrtNumberSumQ

# no functions but dummy variables
tmp
f_
g_
F_
G_
F
G
H
f
g
lst

# inert/lazy trigonometric functions
sin
cos
sec
csc
tan
cot

# auxiliary functions for logging etc
ShowStep
Block

# requires more attention
PosQ[u] # (* If u is not 0 and has a positive form, PosQ[u] returns True, else it returns False. *)
NegQ # negation of PosQ

# Some Qs are defined inside the IntegartionRules folder
# Need to account for this when writing rules
IntegerQ
IntBinomialQ
IntLinearQ
IntQuadraticQ
```

Lastly, I also noted that `Sympy` already uses `Rubi` for their `integrate` method: https://github.com/sympy/sympy/tree/master/sympy/integrals/rubi. See also https://github.com/sympy/sympy/wiki/Rubi-parsing-guide#parsing-tests. Interestingly, it seems they do some preprocessing steps before they actually parse it into `Sympy` syntax.

**Comment by fgerick** [comment]
Thank you so much for this effort, sorry I must have missed this PR from the notifications! It's great to have the tests parsed. 

Regarding your questions: 

I think I used the zip file from the official website (https://rulebasedintegration.org/Rubi-4.16.1.0.zip). But I see now that it is labelled for "Mathematica 7 or later". It does seem handier to have the rules in one line! 

For the integration with Metatheory.jl and Symbolics.jl I do not have any idea and I was hoping for suggestions. In the end this repository was meant to kickstart the progress as I am not familiar with the e-graph theory. I believe the biggest problem is the long list of missing functions, which have some fairly specific functionality that touches the base of Symbolics.jl or SymbolicUtils.jl that are not very mature yet.

**Comment by fatteneder** [comment]
Thanks for merging.

I am also not an expert in either of those packages nor in e-graph theory. But just parsing the rules seems to be a funny exercise :)

Indeed, there are a lot of functions listed, I counted around 300 in here: https://github.com/fgerick/SymbolicRubi.jl/blob/main/gen/scripts/required_functions.txt
If I understand correctly then most of those are implemented in
https://github.com/fgerick/SymbolicRubi.jl/blob/main/gen/Rubi/IntegrationUtilityFunctions.m
in terms of (more or less) atomic/native Mathematica functions.
Perhaps we can tackle the problem by first figuring out which of the basic Mathematica methods we already have and which ones we need to implement.
We can then implement those in `Symbolics.jl, SymbolicUtils.jl`.
Once that is done we can continue by implementing the rest just as it is done in `IntegrationUtilityFunctions.m`. Not saying that this will be the best performant solution, but optimizing can always be done later.


Aside: Given the number of rules (and tests), I can imagine that this might take a while jitting. But I just read here https://symbolics.juliasymbolics.org/dev/manual/io/ that `Symbolics.jl` already provides support for serialization of expressions so that you can package them into a sysimage. I think that can be pretty useful :)

**Comment by fatteneder** [comment]
> ... that touches the base of Symbolics.jl or SymbolicUtils.jl that are not very mature yet.

Here is one issue I opened so far: https://github.com/JuliaSymbolics/Symbolics.jl/issues/622

**Pull request merged**
